version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_pichta
    environment:
      POSTGRES_USER: docker_postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: JobRoadMap
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d JobRoadMap"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d   # Монтируем каталог initdb со скриптами инициализации

  job_road_map:
    restart: always
    image: emperorada/pixta:latest
    tty: true
    container_name: job_road_map
    build: 
      context: ./job_road_map_site
    ports:
      - "8001:8000"
    depends_on:
       postgres-db:
        condition: service_healthy
    volumes:
      - static_volume:/JobRoadMap/job_road_map_site/main/static 
      

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - job_road_map

volumes:
  static_volume:
