# Generated by Django 5.0.1 on 2024-01-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('sex', models.BooleanField()),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edge_id', models.AutoField(primary_key=True, serialize=False)),
                ('edge_from_param', models.CharField(max_length=255)),
                ('edge_to_param', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'edge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrequencyStatistics',
            fields=[
                ('id_frequency_statistics', models.AutoField(primary_key=True, serialize=False)),
                ('count_frequency', models.IntegerField()),
                ('date_operate', models.DateTimeField()),
                ('last_operate', models.BooleanField()),
                ('graph_count', models.IntegerField()),
            ],
            options={
                'db_table': 'frequency_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id_graph', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'graph',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('hint_id', models.AutoField(primary_key=True, serialize=False)),
                ('hint_text', models.TextField()),
            ],
            options={
                'db_table': 'hints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_color_param', models.CharField(max_length=255)),
                ('node_id_param', models.IntegerField()),
                ('node_shape_param', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id_profession', models.AutoField(primary_key=True, serialize=False)),
                ('name_profession', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'profession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionSkill',
            fields=[
                ('id_skill', models.AutoField(primary_key=True, serialize=False)),
                ('name_skill', models.CharField(max_length=255)),
                ('for_graph', models.BooleanField()),
            ],
            options={
                'db_table': 'profession_skill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_me', models.TextField()),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileProfession',
            fields=[
                ('profile_profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date_work', models.DateField()),
                ('end_date_work', models.DateField()),
            ],
            options={
                'db_table': 'profile_profession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileSkills',
            fields=[
                ('id_profile_skills', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profile_skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkillDuration',
            fields=[
                ('id_skill', models.AutoField(primary_key=True, serialize=False)),
                ('duration_for_beginer', models.IntegerField()),
                ('duration_for_advanced', models.IntegerField()),
                ('duration_for_professional', models.IntegerField()),
            ],
            options={
                'db_table': 'skill_duration',
                'managed': False,
            },
        ),
    ]
